const ACTION_TYPE = {
  LEVEL: {
    INIT: 'LEVEL_INIT',
    UPDATE: {
      LIGHTLEVEL: 'LEVEL_UPDATE_LIGHTLEVEL',
      STRUCTURE: 'LEVEL_UPDATE_STRUCTURE',
    },
  },
  ENTITY: {
    MOB: {
      MOVE: 'ENTITY_MOB_MOVE',
    },
  },
  PLAYER: {
    INIT: 'PLAYER_INIT',
    JOIN: 'PLAYER_JOIN',
    LEAVE: 'PLAYER_LEAVE',
    MOVE: 'PLAYER_MOVE',
    INTERACT: 'PLAYER_INTERACT',
  },
  PLAYERS: {
    INIT: 'PLAYERS_INIT',
    JOIN: 'PLAYERS_JOIN',
    LEAVE: 'PLAYERS_LEAVE',
    MOVE: 'PLAYERS_MOVE',
  },
};

Object.freeze(ACTION_TYPE);

export default ACTION_TYPE;
