const EVENT = {
  ELEMENT: {
    CREATE: "ELEMENT_CREATE",
    DESTROY: "ELEMENT_DESTROY",
    UPDATE: "ELEMENT_UPDATE",
  },
  WORLD: {
    DAYLIGHT_CYCLE: "WORLD_DAYLIGHT_CYCLE",
    PLAYERS: {
      JOIN: "WORLD_PLAYERS_JOIN",
      MOVE: "WORLD_PLAYERS_MOVE",
      PICK_UP: "WORLD_PLAYERS_PICK_UP",
    },
  },
  SURFACE: {
    DAYLIGHT_CYCLE: "SURFACE_DAYLIGHT_CYCLE",
    MOB: {
      MOVE: "SURFACE_MOB_MOVE",
    },
  },
  PLAYER: {
    MOVE: "PLAYER_MOVE",
    OBTAIN: "PLAYER_OBTAIN",
  },
  MOB: {
    MOVE: "MOB_MOVE",
  },
};

export default EVENT;
